
var ASSIMP = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ASSIMP) {
  ASSIMP = ASSIMP || {};

var d;d||(d=typeof ASSIMP !== 'undefined' ? ASSIMP : {});var aa={},h;for(h in d)d.hasOwnProperty(h)&&(aa[h]=d[h]);var ca="./this.program",da=!1,q=!1,ea=!1,fa=!1,ha=!1;da="object"===typeof window;q="function"===typeof importScripts;ea=(fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!da&&!q;ha=!da&&!ea&&!q;var r="",ia,ja;
if(ea){r=__dirname+"/";var ka,la;ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);a=ka.readFileSync(a);return b?a:a.toString()};ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",t);d.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=
typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||q)q?r=self.location.href:document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,
r.lastIndexOf("/")+1):r="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ma=d.print||console.log.bind(console),u=d.printErr||console.warn.bind(console);for(h in aa)aa.hasOwnProperty(h)&&(d[h]=aa[h]);aa=null;d.thisProgram&&(ca=d.thisProgram);
function na(a){var b=v[oa>>2];a=b+a+15&-16;a>pa()&&t();v[oa>>2]=a;return b}var qa={"f64-rem":function(a,b){return a%b},"debugger":function(){}},ra=0,sa;d.wasmBinary&&(sa=d.wasmBinary);"object"!==typeof WebAssembly&&u("no native wasm support detected");var x,ta=new WebAssembly.Table({initial:3224,maximum:3224,element:"anyfunc"}),ua=!1;function assert(a,b){a||t("Assertion failed: "+b)}
function va(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var e=y(Math.max(c,1));if(b){a=e;assert(0==(e&3));for(b=e+(c&-4);a<b;a+=4)v[a>>2]=0;for(b=e+c;a<b;)z[a++>>0]=0;return e}a.subarray||a.slice?A.set(a,e):A.set(new Uint8Array(a),e);return e}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&wa)return wa.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function B(a){return a?xa(A,a,void 0):""}
function ya(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=e)break;b[c++]=k}else{if(2047>=k){if(c+1>=e)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++]=224|k>>12}else{if(c+3>=e)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function za(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Aa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,z,A,Ba,Ca,v,C,Da,Ea;
function Fa(a){buffer=a;d.HEAP8=z=new Int8Array(a);d.HEAP16=Ba=new Int16Array(a);d.HEAP32=v=new Int32Array(a);d.HEAPU8=A=new Uint8Array(a);d.HEAPU16=Ca=new Uint16Array(a);d.HEAPU32=C=new Uint32Array(a);d.HEAPF32=Da=new Float32Array(a);d.HEAPF64=Ea=new Float64Array(a)}var oa=129072,Ga=d.TOTAL_MEMORY||16777216;d.wasmMemory?x=d.wasmMemory:x=new WebAssembly.Memory({initial:Ga/65536});x&&(buffer=x.buffer);Ga=buffer.byteLength;Fa(buffer);v[oa>>2]=5372160;
function Ha(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.$;"number"===typeof c?void 0===b.M?d.dynCall_v(c):d.dynCall_vi(c,b.M):c(void 0===b.M?null:b.M)}}}var Ia=[],Ja=[],Ka=[],La=[],Ma=!1;function Na(){var a=d.preRun.shift();Ia.unshift(a)}var Oa=Math.clz32,D=0,Pa=null,Qa=null;d.preloadedImages={};d.preloadedAudios={};function t(a){if(d.onAbort)d.onAbort(a);ma(a);u(a);ua=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}
function Ra(){var a=E;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var E="assimp.wasm";if(!Ra()){var Sa=E;E=d.locateFile?d.locateFile(Sa,r):r+Sa}function Ta(){try{if(sa)return new Uint8Array(sa);if(ja)return ja(E);throw"both async and sync fetching of the wasm failed";}catch(a){t(a)}}
function Ua(){return sa||!da&&!q||"function"!==typeof fetch?new Promise(function(a){a(Ta())}):fetch(E,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+E+"'";return a.arrayBuffer()}).catch(function(){return Ta()})}
d.asm=function(){function a(a){d.asm=a.exports;D--;d.monitorRunDependencies&&d.monitorRunDependencies(D);0==D&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(a=Qa,Qa=null,a()))}function b(b){a(b.instance)}function c(a){return Ua().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){u("failed to asynchronously prepare wasm: "+a);t(a)})}var e={env:Va,wasi_unstable:Va,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:qa};D++;d.monitorRunDependencies&&d.monitorRunDependencies(D);
if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return u("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(sa||"function"!==typeof WebAssembly.instantiateStreaming||Ra()||"function"!==typeof fetch)return c(b);fetch(E,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(b,function(a){u("wasm streaming compile failed: "+a);u("falling back to ArrayBuffer instantiation");c(b)})})})();return{}};Ja.push({$:function(){Wa()}});
function Xa(a){return a.replace(/\b__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}function Ya(){var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack)return"(no stack trace available)"}return a.stack.toString()}var F={};
function Za(a){if(Za.h){var b=v[a>>2];var c=v[b>>2]}else Za.h=!0,F.USER=F.LOGNAME="web_user",F.PATH="/",F.PWD="/",F.HOME="/home/web_user",F.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",F._=ca,c=Ma?y(1024):na(1024),b=Ma?y(256):na(256),v[b>>2]=c,v[a>>2]=b;a=[];var e=0,f;for(f in F)if("string"===typeof F[f]){var g=f+"="+F[f];a.push(g);e+=g.length}if(1024<e)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){e=
g=a[f];for(var k=c,l=0;l<e.length;++l)z[k++>>0]=e.charCodeAt(l);z[k>>0]=0;v[b+4*f>>2]=c;c+=g.length+1}v[b+4*a.length>>2]=0}var G={},$a=[];function ab(a){a&&G[a].P++}function bb(a){if(!a||G[a])return a;for(var b in G)for(var c=+b,e=G[c].W,f=e.length,g=0;g<f;g++)if(e[g]===a)return c;return a}function cb(a){d.___errno_location&&(v[d.___errno_location()>>2]=a);return a}var db=[null,[],[]];function eb(a,b){var c=db[a];0===b||10===b?((1===a?ma:u)(xa(c,0)),c.length=0):c.push(b)}var H=0;
function I(){H+=4;return v[H-4>>2]}var J={};function fb(a,b){if(-1===a||0===b)return-28;var c=J.ea[a];if(!c)return 0;if(b===c.ua){var e=(void 0).sa(c.fd);J.pa(a,e,b,c.flags);(void 0).wa(e);J.ea[a]=null;c.oa&&K(c.va)}return 0}function gb(){return 0}function hb(a,b,c,e){try{for(var f=0,g=0;g<c;g++){for(var k=v[b+8*g>>2],l=v[b+(8*g+4)>>2],n=0;n<l;n++)eb(a,A[k+n]);f+=l}v[e>>2]=f;return 0}catch(m){return t(m),m.u}}
function ib(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function jb(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);kb=a}var kb=void 0;function L(a){for(var b="";A[a];)b+=kb[A[a++]];return b}var M={},O={},lb={};function mb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function nb(a,b){a=mb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function ob(a,b){var c=nb(b,function(a){this.name=b;this.message=a;a=Error(a).stack;void 0!==a&&(this.stack=this.toString()+"\n"+a.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var P=void 0;
function Q(a){throw new P(a);}var pb=void 0;function qb(a){throw new pb(a);}function R(a,b,c){function e(b){b=c(b);b.length!==a.length&&qb("Mismatched type converter count");for(var e=0;e<a.length;++e)S(a[e],b[e])}a.forEach(function(a){lb[a]=b});var f=Array(b.length),g=[],k=0;b.forEach(function(a,b){O.hasOwnProperty(a)?f[b]=O[a]:(g.push(a),M.hasOwnProperty(a)||(M[a]=[]),M[a].push(function(){f[b]=O[a];++k;k===g.length&&e(f)}))});0===g.length&&e(f)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||Q('type "'+e+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.da)return;Q("Cannot register type '"+e+"' twice")}O[a]=b;delete lb[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(a){a()}))}
function rb(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.a.f.b,c=this.a.c,e=a.a.f.b;for(a=a.a.c;b.m;)c=b.G(c),b=b.m;for(;e.m;)a=e.G(a),e=e.m;return b===e&&c===a}function sb(a){return{count:a.count,A:a.A,D:a.D,c:a.c,f:a.f,j:a.j,l:a.l}}function tb(a){Q(a.a.f.b.name+" instance already deleted")}var ub=!1;function vb(){}function wb(a){a.j?a.l.v(a.j):a.f.b.v(a.c)}function xb(a){--a.count.value;0===a.count.value&&wb(a)}
function U(a){if("undefined"===typeof FinalizationGroup)return U=function(a){return a},a;ub=new FinalizationGroup(function(a){for(var b=a.next();!b.done;b=a.next())b=b.value,b.c?xb(b):console.warn("object already deleted: "+b.c)});U=function(a){ub.register(a,a.a,a.a);return a};vb=function(a){ub.unregister(a.a)};return U(a)}
function yb(){this.a.c||tb(this);if(this.a.D)return this.a.count.value+=1,this;var a=U(Object.create(Object.getPrototypeOf(this),{a:{value:sb(this.a)}}));a.a.count.value+=1;a.a.A=!1;return a}function zb(){this.a.c||tb(this);this.a.A&&!this.a.D&&Q("Object already scheduled for deletion");vb(this);xb(this.a);this.a.D||(this.a.j=void 0,this.a.c=void 0)}function Ab(){return!this.a.c}var Bb=void 0,Cb=[];function Db(){for(;Cb.length;){var a=Cb.pop();a.a.A=!1;a["delete"]()}}
function Eb(){this.a.c||tb(this);this.a.A&&!this.a.D&&Q("Object already scheduled for deletion");Cb.push(this);1===Cb.length&&Bb&&Bb(Db);this.a.A=!0;return this}function Fb(){T.prototype.isAliasOf=rb;T.prototype.clone=yb;T.prototype["delete"]=zb;T.prototype.isDeleted=Ab;T.prototype.deleteLater=Eb}function T(){}var Gb={};
function Hb(a,b,c){if(void 0===a[b].g){var e=a[b];a[b]=function(){a[b].g.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].g+")!");return a[b].g[arguments.length].apply(this,arguments)};a[b].g=[];a[b].g[e.w]=e}}
function Ib(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].g&&void 0!==d[a].g[c])&&Q("Cannot register public name '"+a+"' twice"),Hb(d,a,a),d.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].g[c]=b):(d[a]=b,void 0!==c&&(d[a].xa=c))}function Jb(a,b,c,e,f,g,k,l){this.name=a;this.constructor=b;this.B=c;this.v=e;this.m=f;this.aa=g;this.G=k;this.Z=l;this.ga=[]}
function Kb(a,b,c){for(;b!==c;)b.G||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.G(a),b=b.m;return a}function Lb(a,b){if(null===b)return this.O&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);return Kb(b.a.c,b.a.f.b,this.b)}
function Mb(a,b){if(null===b){this.O&&Q("null is not a valid "+this.name);if(this.I){var c=this.ha();null!==a&&a.push(this.v,c);return c}return 0}b.a||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.H&&b.a.f.H&&Q("Cannot convert argument of type "+(b.a.l?b.a.l.name:b.a.f.name)+" to parameter type "+this.name);c=Kb(b.a.c,b.a.f.b,this.b);if(this.I)switch(void 0===b.a.j&&Q("Passing raw pointer to smart pointer is illegal"),this.ja){case 0:b.a.l===
this?c=b.a.j:Q("Cannot convert argument of type "+(b.a.l?b.a.l.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:c=b.a.j;break;case 2:if(b.a.l===this)c=b.a.j;else{var e=b.clone();c=this.ia(c,Nb(function(){e["delete"]()}));null!==a&&a.push(this.v,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Ob(a,b){if(null===b)return this.O&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.H&&Q("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return Kb(b.a.c,b.a.f.b,this.b)}function Pb(a){return this.fromWireType(C[a>>2])}function Qb(a){this.V&&(a=this.V(a));return a}function Rb(a){this.v&&this.v(a)}function Sb(a){if(null!==a)a["delete"]()}
function Tb(a,b,c){if(b===c)return a;if(void 0===c.m)return null;a=Tb(a,b,c.m);return null===a?null:c.Z(a)}function Ub(){return Object.keys(Vb).length}function Wb(){var a=[],b;for(b in Vb)Vb.hasOwnProperty(b)&&a.push(Vb[b]);return a}function Xb(a){Bb=a;Cb.length&&Bb&&Bb(Db)}function Yb(){d.getInheritedInstanceCount=Ub;d.getLiveInheritedInstances=Wb;d.flushPendingDeletes=Db;d.setDelayFunction=Xb}var Vb={};
function Zb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.m;)b=a.G(b),a=a.m;return b}function $b(a,b){b=Zb(a,b);return Vb[b]}function ac(a,b){b.f&&b.c||qb("makeClassHandle requires ptr and ptrType");!!b.l!==!!b.j&&qb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return U(Object.create(a,{a:{value:b}}))}
function bc(a){function b(){return this.I?ac(this.b.B,{f:this.fa,c:c,l:this,j:a}):ac(this.b.B,{f:this,c:a})}var c=this.ba(a);if(!c)return this.N(a),null;var e=$b(this.b,c);if(void 0!==e){if(0===e.a.count.value)return e.a.c=c,e.a.j=a,e.clone();e=e.clone();this.N(a);return e}e=this.b.aa(c);e=Gb[e];if(!e)return b.call(this);e=this.H?e.X:e.pointerType;var f=Tb(c,this.b,e.b);return null===f?b.call(this):this.I?ac(e.b.B,{f:e,c:f,l:this,j:a}):ac(e.b.B,{f:e,c:f})}
function cc(){W.prototype.ba=Qb;W.prototype.N=Rb;W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=Pb;W.prototype.deleteObject=Sb;W.prototype.fromWireType=bc}function W(a,b,c,e,f,g,k,l,n,m,p){this.name=a;this.b=b;this.O=c;this.H=e;this.I=f;this.fa=g;this.ja=k;this.V=l;this.ha=n;this.ia=m;this.v=p;f||void 0!==b.m?this.toWireType=Mb:(this.toWireType=e?Lb:Ob,this.o=null)}
function dc(a,b,c){d.hasOwnProperty(a)||qb("Replacing nonexistant public symbol");void 0!==d[a].g&&void 0!==c?d[a].g[c]=b:(d[a]=b,d[a].w=c)}
function X(a,b){a=L(a);if(void 0!==d["FUNCTION_TABLE_"+a])var c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d["dynCall_"+a];void 0===c&&(c=d["dynCall_"+a.replace(/f/g,"d")],void 0===c&&Q("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var ec=void 0;function fc(a){a=hc(a);var b=L(a);K(a);return b}function ic(a,b){function c(a){f[a]||O[a]||(lb[a]?lb[a].forEach(c):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(c);throw new ec(a+": "+e.map(fc).join([", "]));}
function jc(a,b){if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=nb(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;c=new c;a=a.apply(c,b);return a instanceof Object?a:c}function kc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function lc(a,b,c,e,f){var g=b.length;2>g&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].o){l=!0;break}var n="void"!==b[0].name,m="",p="";for(c=0;c<g-2;++c)m+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+mb(a)+"("+m+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var w=l?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");e=[Q,e,f,kc,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+w+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+w+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),e.push(b[c+2]);k&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(n?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].o&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",m.push(g+"_dtor"),e.push(b[c].o));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return jc(Function,m).apply(null,e)}function mc(a,b){for(var c=[],e=0;e<a;e++)c.push(v[(b>>2)+e]);return c}var nc=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function oc(a){4<a&&0===--Y[a].P&&(Y[a]=void 0,nc.push(a))}function pc(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a}function qc(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null}function rc(){d.count_emval_handles=pc;d.get_first_emval=qc}function Nb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=nc.length?nc.pop():Y.length;Y[b]={P:1,value:a};return b}}
function sc(a,b,c){switch(b){case 0:return function(a){return this.fromWireType((c?z:A)[a])};case 1:return function(a){return this.fromWireType((c?Ba:Ca)[a>>1])};case 2:return function(a){return this.fromWireType((c?v:C)[a>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function tc(a,b){var c=O[a];void 0===c&&Q(b+" has unknown type "+fc(a));return c}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function uc(a,b){switch(b){case 2:return function(a){return this.fromWireType(Da[a>>2])};case 3:return function(a){return this.fromWireType(Ea[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function vc(a,b,c){switch(b){case 0:return c?function(a){return z[a]}:function(a){return A[a]};case 1:return c?function(a){return Ba[a>>1]}:function(a){return Ca[a>>1]};case 2:return c?function(a){return v[a>>2]}:function(a){return C[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function wc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!wc.h){wc.h=!0;v[xc()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);v[yc()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var e=a(c),f=a(b);e=va(zc(e));f=va(zc(f));b.getTimezoneOffset()<c.getTimezoneOffset()?(v[Ac()>>2]=e,v[Ac()+4>>2]=f):(v[Ac()>>2]=f,v[Ac()+4>>2]=e)}}
function Bc(a,b){var c=v[a>>2],e=v[a+4>>2],f=v[a+8>>2],g=v[a+12>>2];ya("Sun Mon Tue Wed Thu Fri Sat".split(" ")[v[a+24>>2]]+" "+"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[v[a+16>>2]]+(10>g?"  ":" ")+g+(10>f?" 0":" ")+f+(10>e?":0":":")+e+(10>c?":0":":")+c+" "+(1900+v[a+20>>2])+"\n",A,b,26);return b}function Cc(){void 0===Cc.start&&(Cc.start=Date.now());return 1E3*(Date.now()-Cc.start)|0}function pa(){return z.length}
function Dc(a){try{return x.grow(a-buffer.byteLength+65535>>16),Fa(x.buffer),1}catch(b){}}function Ec(a){if(0===a)return 0;a=B(a);if(!F.hasOwnProperty(a))return 0;Ec.h&&K(Ec.h);a=F[a];var b=za(a)+1,c=y(b);c&&ya(a,z,c,b);Ec.h=c;return Ec.h}ya("GMT",A,129168,4);
function Fc(a,b){a=new Date(1E3*v[a>>2]);v[b>>2]=a.getUTCSeconds();v[b+4>>2]=a.getUTCMinutes();v[b+8>>2]=a.getUTCHours();v[b+12>>2]=a.getUTCDate();v[b+16>>2]=a.getUTCMonth();v[b+20>>2]=a.getUTCFullYear()-1900;v[b+24>>2]=a.getUTCDay();v[b+36>>2]=0;v[b+32>>2]=0;v[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;v[b+40>>2]=129168;return b}function Z(){Z.h||(Z.h=[]);Z.h.push(Gc());return Z.h.length-1}
function Hc(a,b){wc();a=new Date(1E3*v[a>>2]);v[b>>2]=a.getSeconds();v[b+4>>2]=a.getMinutes();v[b+8>>2]=a.getHours();v[b+12>>2]=a.getDate();v[b+16>>2]=a.getMonth();v[b+20>>2]=a.getFullYear()-1900;v[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);v[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;v[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(e!=c&&a.getTimezoneOffset()==Math.min(c,e))|0;v[b+32>>2]=a;a=v[Ac()+(a?4:0)>>2];
v[b+40>>2]=a;return b}function Ic(a){return 0===a%4&&(0!==a%100||0===a%400)}function Jc(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var Kc=[31,29,31,30,31,30,31,31,30,31,30,31],Lc=[31,28,31,30,31,30,31,31,30,31,30,31];function Mc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Ic(a.getFullYear())?Kc:Lc)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Nc(a,b,c,e){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var e;0===(e=c(a.getFullYear()-b.getFullYear()))&&0===(e=c(a.getMonth()-b.getMonth()))&&(e=c(a.getDate()-b.getDate()));return e}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function n(a){a=Mc(new Date(a.i+1900,0,1),a.L);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=k(l(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var m=v[e+40>>2];e={ma:v[e>>2],la:v[e+4>>2],J:v[e+8>>2],F:v[e+12>>2],C:v[e+16>>2],i:v[e+20>>2],K:v[e+24>>2],L:v[e+28>>2],ya:v[e+32>>2],ka:v[e+36>>2],na:m?B(m):
""};c=B(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ba="January February March April May June July August September October November December".split(" ");m={"%a":function(a){return w[a.K].substring(0,3)},"%A":function(a){return w[a.K]},"%b":function(a){return ba[a.C].substring(0,3)},"%B":function(a){return ba[a.C]},"%C":function(a){return g((a.i+1900)/100|0,2)},"%d":function(a){return g(a.F,2)},"%e":function(a){return f(a.F,2," ")},"%g":function(a){return n(a).toString().substring(2)},"%G":function(a){return n(a)},"%H":function(a){return g(a.J,2)},
"%I":function(a){a=a.J;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.F+Jc(Ic(a.i+1900)?Kc:Lc,a.C-1),3)},"%m":function(a){return g(a.C+1,2)},"%M":function(a){return g(a.la,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.J&&12>a.J?"AM":"PM"},"%S":function(a){return g(a.ma,2)},"%t":function(){return"\t"},"%u":function(a){return a.K||7},"%U":function(a){var b=new Date(a.i+1900,0,1),c=0===b.getDay()?b:Mc(b,7-b.getDay());a=new Date(a.i+1900,a.C,a.F);return 0>k(c,a)?g(Math.ceil((31-
c.getDate()+(Jc(Ic(a.getFullYear())?Kc:Lc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.i+1900,0,4)),c=l(new Date(a.i+1901,0,4)),e=Mc(new Date(a.i+1900,0,1),a.L);return 0>k(e,b)?"53":0>=k(c,e)?"01":g(Math.ceil((b.getFullYear()<a.i+1900?a.L+32-b.getDate():a.L+1-b.getDate())/7),2)},"%w":function(a){return a.K},"%W":function(a){var b=new Date(a.i,0,1),c=1===b.getDay()?b:Mc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.i+1900,a.C,a.F);return 0>k(c,
a)?g(Math.ceil((31-c.getDate()+(Jc(Ic(a.getFullYear())?Kc:Lc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.i+1900).toString().substring(2)},"%Y":function(a){return a.i+1900},"%z":function(a){a=a.ka;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.na},"%%":function(){return"%"}};for(p in m)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),m[p](e)));p=zc(c,!1);if(p.length>b)return 0;z.set(p,a);return p.length-
1}jb();P=d.BindingError=ob(Error,"BindingError");pb=d.InternalError=ob(Error,"InternalError");Fb();cc();Yb();ec=d.UnboundTypeError=ob(Error,"UnboundTypeError");rc();function zc(a,b){var c=Array(za(a)+1);a=ya(a,c,0,c.length);b&&(c.length=a);return c}
var Va={ClassHandle:T,ClassHandle_clone:yb,ClassHandle_delete:zb,ClassHandle_deleteLater:Eb,ClassHandle_isAliasOf:rb,ClassHandle_isDeleted:Ab,RegisteredClass:Jb,RegisteredPointer:W,RegisteredPointer_deleteObject:Sb,RegisteredPointer_destructor:Rb,RegisteredPointer_fromWireType:bc,RegisteredPointer_getPointee:Qb,___assert_fail:function(a,b,c,e){t("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,e?B(e):"unknown function"])},___buildEnvironment:Za,___cxa_allocate_exception:function(a){return y(a)},
___cxa_begin_catch:function(a){var b=G[a];b&&!b.T&&(b.T=!0,Oc.S--);b&&(b.R=!1);$a.push(a);ab(bb(a));return a},___cxa_rethrow:function(){var a=$a.pop();a=bb(a);G[a].R||($a.push(a),G[a].R=!0);throw a;},___cxa_throw:function(a,b,c){G[a]={c:a,W:[a],type:b,N:c,P:0,T:!1,R:!1};"uncaught_exception"in Oc?Oc.S++:Oc.S=1;throw a;},___exception_addRef:ab,___exception_deAdjust:bb,___gxx_personality_v0:function(){},___lock:function(){},___map_file:function(){cb(63);return-1},___setErrNo:cb,___syscall140:function(a,
b){H=b;try{return J.U(),I(),I(),I(),I(),0}catch(c){return t(c),-c.u}},___syscall145:function(a,b){H=b;try{var c=J.U(),e=I(),f=I();return J.ra(c,e,f)}catch(g){return t(g),-g.u}},___syscall195:function(a,b){H=b;try{var c=B(I()),e=I();return J.Y((void 0).stat,c,e)}catch(f){return t(f),-f.u}},___syscall197:function(a,b){H=b;try{var c=J.U(),e=I();return J.Y((void 0).stat,c.path,e)}catch(f){return t(f),-f.u}},___syscall221:function(a,b){H=b;return 0},___syscall5:function(a,b){H=b;try{var c=B(I()),e=I(),
f=I();return(void 0).open(c,e,f).fd}catch(g){return t(g),-g.u}},___syscall54:function(a,b){H=b;return 0},___syscall85:function(a,b){H=b;try{var c=B(I()),e=I(),f=I();return J.qa(c,e,f)}catch(g){return t(g),-g.u}},___syscall91:function(a,b){H=b;try{var c=I(),e=I();return fb(c,e)}catch(f){return t(f),-f.u}},___unlock:function(){},___wasi_fd_close:function(){return gb.apply(null,arguments)},___wasi_fd_write:function(){return hb.apply(null,arguments)},__addDays:Mc,__arraySum:Jc,__embind_register_bool:function(a,
b,c,e,f){var g=ib(c);b=L(b);S(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var e=z;else if(2===c)e=Ba;else if(4===c)e=v;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>g])},o:null})},__embind_register_class:function(a,b,c,e,f,g,k,l,n,m,p,w,ba){p=L(p);g=X(f,g);l&&(l=X(k,l));m&&(m=X(n,m));ba=X(w,ba);var N=mb(p);Ib(N,function(){ic("Cannot construct "+p+" due to unbound types",
[e])});R([a,b,c],e?[e]:[],function(b){b=b[0];if(e){var c=b.b;var f=c.B}else f=T.prototype;b=nb(N,function(){if(Object.getPrototypeOf(this)!==k)throw new P("Use 'new' to construct "+p);if(void 0===n.s)throw new P(p+" has no accessible constructor");var a=n.s[arguments.length];if(void 0===a)throw new P("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(n.s).toString()+") parameters instead!");return a.apply(this,arguments)});var k=Object.create(f,
{constructor:{value:b}});b.prototype=k;var n=new Jb(p,b,k,ba,c,g,l,m);c=new W(p,n,!0,!1,!1);f=new W(p+"*",n,!1,!1,!1);var w=new W(p+" const*",n,!1,!0,!1);Gb[a]={pointerType:f,X:w};dc(N,b);return[c,f,w]})},__embind_register_class_class_function:function(a,b,c,e,f,g,k){var l=mc(c,e);b=L(b);g=X(f,g);R([],[a],function(a){function e(){ic("Cannot call "+f+" due to unbound types",l)}a=a[0];var f=a.name+"."+b,n=a.b.constructor;void 0===n[b]?(e.w=c-1,n[b]=e):(Hb(n,b,f),n[b].g[c-1]=e);R([],l,function(a){a=
[a[0],null].concat(a.slice(1));a=lc(f,a,null,g,k);void 0===n[b].g?(a.w=c-1,n[b]=a):n[b].g[c-1]=a;return[]});return[]})},__embind_register_class_constructor:function(a,b,c,e,f,g){var k=mc(b,c);f=X(e,f);R([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.b.s&&(a.b.s=[]);if(void 0!==a.b.s[b-1])throw new P("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
a.b.s[b-1]=function(){ic("Cannot construct "+a.name+" due to unbound types",k)};R([],k,function(e){a.b.s[b-1]=function(){arguments.length!==b-1&&Q(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],k=Array(b);k[0]=g;for(var l=1;l<b;++l)k[l]=e[l].toWireType(a,arguments[l-1]);k=f.apply(null,k);kc(a);return e[0].fromWireType(k)};return[]});return[]})},__embind_register_class_function:function(a,b,c,e,f,g,k,l){var n=mc(c,e);b=L(b);g=X(f,g);R([],[a],function(a){function e(){ic("Cannot call "+
f+" due to unbound types",n)}a=a[0];var f=a.name+"."+b;l&&a.b.ga.push(b);var m=a.b.B,N=m[b];void 0===N||void 0===N.g&&N.className!==a.name&&N.w===c-2?(e.w=c-2,e.className=a.name,m[b]=e):(Hb(m,b,f),m[b].g[c-2]=e);R([],n,function(e){e=lc(f,e,a,g,k);void 0===m[b].g?(e.w=c-2,m[b]=e):m[b].g[c-2]=e;return[]});return[]})},__embind_register_emval:function(a,b){b=L(b);S(a,{name:b,fromWireType:function(a){var b=Y[a].value;oc(a);return b},toWireType:function(a,b){return Nb(b)},argPackAdvance:8,readValueFromPointer:Pb,
o:null})},__embind_register_enum:function(a,b,c,e){function f(){}c=ib(c);b=L(b);f.values={};S(a,{name:b,constructor:f,fromWireType:function(a){return this.constructor.values[a]},toWireType:function(a,b){return b.value},argPackAdvance:8,readValueFromPointer:sc(b,c,e),o:null});Ib(b,f)},__embind_register_enum_value:function(a,b,c){var e=tc(a,"enum");b=L(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:nb(e.name+"_"+b,function(){})}});a.values[c]=e;a[b]=e},
__embind_register_float:function(a,b,c){c=ib(c);b=L(b);S(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+V(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:uc(b,c),o:null})},__embind_register_function:function(a,b,c,e,f,g){var k=mc(b,c);a=L(a);f=X(e,f);Ib(a,function(){ic("Cannot call "+a+" due to unbound types",k)},b-1);R([],k,function(c){c=[c[0],null].concat(c.slice(1));
dc(a,lc(a,c,null,f,g),b-1);return[]})},__embind_register_integer:function(a,b,c,e,f){function g(a){return a}b=L(b);-1===f&&(f=4294967295);var k=ib(c);if(0===e){var l=32-8*c;g=function(a){return a<<l>>>l}}var n=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+V(c)+'" to '+this.name);if(c<e||c>f)throw new TypeError('Passing a number "'+V(c)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+e+", "+f+"]!");return n?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:vc(b,k,0!==e),o:null})},__embind_register_memory_view:function(a,b,c){function e(a){a>>=2;var b=C;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);S(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{da:!0})},__embind_register_std_string:function(a,b){b=L(b);var c="std::string"===
b;S(a,{name:b,fromWireType:function(a){var b=C[a>>2];if(c){var e=A[a+4+b],k=0;0!=e&&(k=e,A[a+4+b]=0);var l=a+4;for(e=0;e<=b;++e){var n=a+4+e;if(0==A[n]){l=B(l);if(void 0===m)var m=l;else m+=String.fromCharCode(0),m+=l;l=n+1}}0!=k&&(A[a+4+b]=k)}else{m=Array(b);for(e=0;e<b;++e)m[e]=String.fromCharCode(A[a+4+e]);m=m.join("")}K(a);return m},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var e="string"===typeof b;e||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof
Int8Array||Q("Cannot pass non-string to std::string");var f=(c&&e?function(){return za(b)}:function(){return b.length})(),l=y(4+f+1);C[l>>2]=f;if(c&&e)ya(b,A,l+4,f+1);else if(e)for(e=0;e<f;++e){var n=b.charCodeAt(e);255<n&&(K(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+e]=n}else for(e=0;e<f;++e)A[l+4+e]=b[e];null!==a&&a.push(K,l);return l},argPackAdvance:8,readValueFromPointer:Pb,o:function(a){K(a)}})},__embind_register_std_wstring:function(a,b,c){c=L(c);if(2===b){var e=
function(){return Ca};var f=1}else 4===b&&(e=function(){return C},f=2);S(a,{name:c,fromWireType:function(a){for(var b=e(),c=C[a>>2],g=Array(c),m=a+4>>f,p=0;p<c;++p)g[p]=String.fromCharCode(b[m+p]);K(a);return g.join("")},toWireType:function(a,c){var g=c.length,k=y(4+g*b),m=e();C[k>>2]=g;for(var p=k+4>>f,w=0;w<g;++w)m[p+w]=c.charCodeAt(w);null!==a&&a.push(K,k);return k},argPackAdvance:8,readValueFromPointer:Pb,o:function(a){K(a)}})},__embind_register_void:function(a,b){b=L(b);S(a,{ta:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},__emscripten_syscall_munmap:fb,__emval_decref:oc,__emval_register:Nb,__isLeapYear:Ic,__memory_base:1024,__table_base:0,_abort:function(){t()},_asctime:function(a){return Bc(a,129184)},_asctime_r:Bc,_clock:Cc,_embind_repr:V,_emscripten_get_heap_size:pa,_emscripten_memcpy_big:function(a,b,c){A.set(A.subarray(b,b+c),a)},_emscripten_resize_heap:function(a){if(2147418112<a)return!1;for(var b=Math.max(pa(),16777216);b<a;)536870912>=b?b=Aa(2*b):b=Math.min(Aa((3*
b+2147483648)/4),2147418112);return Dc(b)?!0:!1},_fd_close:gb,_fd_write:hb,_getenv:Ec,_gmtime:function(a){return Fc(a,129120)},_gmtime_r:Fc,_llvm_cttz_i32:function(a){a|=0;return(a?31-(Oa(a^a-1)|0)|0:32)|0},_llvm_stackrestore:function(a){var b=Z.h[a];Z.h.splice(a,1);Pc(b)},_llvm_stacksave:Z,_llvm_trap:function(){t("trap!")},_localtime:function(a){return Hc(a,129120)},_localtime_r:Hc,_mktime:function(a){wc();var b=new Date(v[a+20>>2]+1900,v[a+16>>2],v[a+12>>2],v[a+8>>2],v[a+4>>2],v[a>>2],0),c=v[a+
32>>2],e=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),l=Math.min(k,g);0>c?v[a+32>>2]=Number(g!=k&&l==e):0<c!=(l==e)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?l:g)-e)));v[a+24>>2]=b.getDay();v[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},_strftime:Nc,_strftime_l:function(a,b,c,e){return Nc(a,b,c,e)},_time:function(a){var b=Date.now()/1E3|0;a&&(v[a>>2]=b);return b},_tzset:wc,abort:t,
abortOnCannotGrowMemory:function(){t("OOM")},attachFinalizer:U,constNoSmartPtrRawPointerToWireType:Lb,count_emval_handles:pc,craftInvokerFunction:lc,createNamedFunction:nb,demangle:function(a){return a},demangleAll:Xa,detachFinalizer:vb,downcastPointer:Tb,embind__requireFunction:X,embind_init_charCodes:jb,emscripten_realloc_buffer:Dc,ensureOverloadTable:Hb,enumReadValueFromPointer:sc,exposePublicSymbol:Ib,extendError:ob,floatReadValueFromPointer:uc,flushPendingDeletes:Db,flush_NO_FILESYSTEM:function(){var a=
d._fflush;a&&a(0);db[1].length&&eb(1,10);db[2].length&&eb(2,10)},genericPointerToWireType:Mb,getBasestPointer:Zb,getInheritedInstance:$b,getInheritedInstanceCount:Ub,getLiveInheritedInstances:Wb,getShiftFromSize:ib,getTempRet0:function(){return ra},getTypeName:fc,get_first_emval:qc,heap32VectorToArray:mc,init_ClassHandle:Fb,init_RegisteredPointer:cc,init_embind:Yb,init_emval:rc,integerReadValueFromPointer:vc,jsStackTrace:Ya,makeClassHandle:ac,makeLegalFunctionName:mb,memory:x,new_:jc,nonConstNoSmartPtrRawPointerToWireType:Ob,
readLatin1String:L,registerType:S,releaseClassHandle:xb,replacePublicSymbol:dc,requireRegisteredType:tc,runDestructor:wb,runDestructors:kc,setDelayFunction:Xb,setTempRet0:function(a){ra=a},shallowCopyInternalPointer:sb,simpleReadValueFromPointer:Pb,stackTrace:function(){var a=Ya();d.extraStackTrace&&(a+="\n"+d.extraStackTrace());return Xa(a)},table:ta,tempDoublePtr:129264,throwBindingError:Q,throwInstanceAlreadyDeleted:tb,throwInternalError:qb,throwUnboundTypeError:ic,upcastPointer:Kb,whenDependentTypesAreResolved:R},
Qc=d.asm({},Va,buffer);d.asm=Qc;var Oc=d.__ZSt18uncaught_exceptionv=function(){return d.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)};d.___cxa_can_catch=function(){return d.asm.___cxa_can_catch.apply(null,arguments)};d.___cxa_is_pointer_type=function(){return d.asm.___cxa_is_pointer_type.apply(null,arguments)};d.___divdi3=function(){return d.asm.___divdi3.apply(null,arguments)};
d.___embind_register_native_and_builtin_types=function(){return d.asm.___embind_register_native_and_builtin_types.apply(null,arguments)};var hc=d.___getTypeName=function(){return d.asm.___getTypeName.apply(null,arguments)};d.___muldi3=function(){return d.asm.___muldi3.apply(null,arguments)};d.___udivdi3=function(){return d.asm.___udivdi3.apply(null,arguments)};
var yc=d.__get_daylight=function(){return d.asm.__get_daylight.apply(null,arguments)},xc=d.__get_timezone=function(){return d.asm.__get_timezone.apply(null,arguments)},Ac=d.__get_tzname=function(){return d.asm.__get_tzname.apply(null,arguments)};d._bitshift64Lshr=function(){return d.asm._bitshift64Lshr.apply(null,arguments)};d._bitshift64Shl=function(){return d.asm._bitshift64Shl.apply(null,arguments)};d._emscripten_get_sbrk_ptr=function(){return d.asm._emscripten_get_sbrk_ptr.apply(null,arguments)};
d._emscripten_replace_memory=function(){return d.asm._emscripten_replace_memory.apply(null,arguments)};var K=d._free=function(){return d.asm._free.apply(null,arguments)};d._i64Add=function(){return d.asm._i64Add.apply(null,arguments)};d._i64Subtract=function(){return d.asm._i64Subtract.apply(null,arguments)};d._llvm_bswap_i16=function(){return d.asm._llvm_bswap_i16.apply(null,arguments)};d._llvm_bswap_i32=function(){return d.asm._llvm_bswap_i32.apply(null,arguments)};
var y=d._malloc=function(){return d.asm._malloc.apply(null,arguments)};d._memcpy=function(){return d.asm._memcpy.apply(null,arguments)};d._memmove=function(){return d.asm._memmove.apply(null,arguments)};d._memset=function(){return d.asm._memset.apply(null,arguments)};d.establishStackSpace=function(){return d.asm.establishStackSpace.apply(null,arguments)};var Wa=d.globalCtors=function(){return d.asm.globalCtors.apply(null,arguments)};d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)};
var Pc=d.stackRestore=function(){return d.asm.stackRestore.apply(null,arguments)},Gc=d.stackSave=function(){return d.asm.stackSave.apply(null,arguments)};d.dynCall_di=function(){return d.asm.dynCall_di.apply(null,arguments)};d.dynCall_dii=function(){return d.asm.dynCall_dii.apply(null,arguments)};d.dynCall_fi=function(){return d.asm.dynCall_fi.apply(null,arguments)};d.dynCall_fii=function(){return d.asm.dynCall_fii.apply(null,arguments)};
d.dynCall_fiif=function(){return d.asm.dynCall_fiif.apply(null,arguments)};d.dynCall_fiii=function(){return d.asm.dynCall_fiii.apply(null,arguments)};d.dynCall_fiiif=function(){return d.asm.dynCall_fiiif.apply(null,arguments)};d.dynCall_fiiii=function(){return d.asm.dynCall_fiiii.apply(null,arguments)};d.dynCall_fiiiii=function(){return d.asm.dynCall_fiiiii.apply(null,arguments)};d.dynCall_i=function(){return d.asm.dynCall_i.apply(null,arguments)};
d.dynCall_ifi=function(){return d.asm.dynCall_ifi.apply(null,arguments)};d.dynCall_ifii=function(){return d.asm.dynCall_ifii.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.dynCall_ii.apply(null,arguments)};d.dynCall_iidi=function(){return d.asm.dynCall_iidi.apply(null,arguments)};d.dynCall_iif=function(){return d.asm.dynCall_iif.apply(null,arguments)};d.dynCall_iiff=function(){return d.asm.dynCall_iiff.apply(null,arguments)};
d.dynCall_iifff=function(){return d.asm.dynCall_iifff.apply(null,arguments)};d.dynCall_iiffff=function(){return d.asm.dynCall_iiffff.apply(null,arguments)};d.dynCall_iifffffffff=function(){return d.asm.dynCall_iifffffffff.apply(null,arguments)};d.dynCall_iiffffffffffffffff=function(){return d.asm.dynCall_iiffffffffffffffff.apply(null,arguments)};d.dynCall_iifi=function(){return d.asm.dynCall_iifi.apply(null,arguments)};d.dynCall_iifii=function(){return d.asm.dynCall_iifii.apply(null,arguments)};
d.dynCall_iii=function(){return d.asm.dynCall_iii.apply(null,arguments)};d.dynCall_iiif=function(){return d.asm.dynCall_iiif.apply(null,arguments)};d.dynCall_iiifff=function(){return d.asm.dynCall_iiifff.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};d.dynCall_iiiif=function(){return d.asm.dynCall_iiiif.apply(null,arguments)};d.dynCall_iiiii=function(){return d.asm.dynCall_iiiii.apply(null,arguments)};
d.dynCall_iiiiid=function(){return d.asm.dynCall_iiiiid.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.dynCall_iiiiii.apply(null,arguments)};d.dynCall_iiiiiid=function(){return d.asm.dynCall_iiiiiid.apply(null,arguments)};d.dynCall_iiiiiii=function(){return d.asm.dynCall_iiiiiii.apply(null,arguments)};d.dynCall_iiiiiiii=function(){return d.asm.dynCall_iiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiii=function(){return d.asm.dynCall_iiiiiiiii.apply(null,arguments)};
d.dynCall_iiiiiiiiii=function(){return d.asm.dynCall_iiiiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiiiii=function(){return d.asm.dynCall_iiiiiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiiiiiiiiiii=function(){return d.asm.dynCall_iiiiiiiiiiiiiiiii.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};d.dynCall_vi=function(){return d.asm.dynCall_vi.apply(null,arguments)};d.dynCall_vid=function(){return d.asm.dynCall_vid.apply(null,arguments)};
d.dynCall_vif=function(){return d.asm.dynCall_vif.apply(null,arguments)};d.dynCall_viff=function(){return d.asm.dynCall_viff.apply(null,arguments)};d.dynCall_vifff=function(){return d.asm.dynCall_vifff.apply(null,arguments)};d.dynCall_viffff=function(){return d.asm.dynCall_viffff.apply(null,arguments)};d.dynCall_vifffffffff=function(){return d.asm.dynCall_vifffffffff.apply(null,arguments)};d.dynCall_viffffffffffffffff=function(){return d.asm.dynCall_viffffffffffffffff.apply(null,arguments)};
d.dynCall_vii=function(){return d.asm.dynCall_vii.apply(null,arguments)};d.dynCall_viid=function(){return d.asm.dynCall_viid.apply(null,arguments)};d.dynCall_viif=function(){return d.asm.dynCall_viif.apply(null,arguments)};d.dynCall_viiff=function(){return d.asm.dynCall_viiff.apply(null,arguments)};d.dynCall_viifff=function(){return d.asm.dynCall_viifff.apply(null,arguments)};d.dynCall_viiffff=function(){return d.asm.dynCall_viiffff.apply(null,arguments)};
d.dynCall_viifffffffff=function(){return d.asm.dynCall_viifffffffff.apply(null,arguments)};d.dynCall_viiffffffffffffffff=function(){return d.asm.dynCall_viiffffffffffffffff.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.dynCall_viii.apply(null,arguments)};d.dynCall_viiif=function(){return d.asm.dynCall_viiif.apply(null,arguments)};d.dynCall_viiiff=function(){return d.asm.dynCall_viiiff.apply(null,arguments)};d.dynCall_viiifff=function(){return d.asm.dynCall_viiifff.apply(null,arguments)};
d.dynCall_viiii=function(){return d.asm.dynCall_viiii.apply(null,arguments)};d.dynCall_viiiif=function(){return d.asm.dynCall_viiiif.apply(null,arguments)};d.dynCall_viiiiff=function(){return d.asm.dynCall_viiiiff.apply(null,arguments)};d.dynCall_viiiifff=function(){return d.asm.dynCall_viiiifff.apply(null,arguments)};d.dynCall_viiiii=function(){return d.asm.dynCall_viiiii.apply(null,arguments)};d.dynCall_viiiiii=function(){return d.asm.dynCall_viiiiii.apply(null,arguments)};d.asm=Qc;var Rc;
d.then=function(a){if(Rc)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};Qa=function Sc(){Rc||Tc();Rc||(Qa=Sc)};
function Tc(){function a(){if(!Rc&&(Rc=!0,!ua)){Ma=!0;Ha(Ja);Ha(Ka);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();La.unshift(a)}Ha(La)}}if(!(0<D)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Na();Ha(Ia);0<D||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=Tc;
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();Tc();


  return ASSIMP
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ASSIMP;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ASSIMP; });
    else if (typeof exports === 'object')
      exports["ASSIMP"] = ASSIMP;
    